name: riverpod_skeleton
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  go_router: ^5.2.4 # or the latest version from pub.dev
  easy_localization: ^3.0.1
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  flutter_riverpod: ^2.1.1
  dartz: ^0.10.1
  json_annotation: ^4.7.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
